version: "3.8"
services:
  mapstore:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OVR: "geostore-datasource-ovr.properties"
        MAPSTORE_WEBAPP_SRC: "https://github.com/geosolutions-it/MapStore2/releases/latest/download/mapstore.war"
    container_name: mapstore
    command: [ "catalina.sh", "run" ]
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - mapstore-network

  postgres:
    build:
      context: ./docker/postgres/
    image: geosolutions-mapstore/postgis
    container_name: postgres
    restart: on-failure
    healthcheck:
      test: /usr/bin/pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geostore
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - mapstore-network

  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./docker/mapstore.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - "8081:80"
    depends_on:
      - mapstore
    networks:
      - mapstore-network

volumes:
  pg_data:

networks:
  mapstore-network:
    driver: bridge

